"""
UCS MULTIPLE-DEPTH SYNTHETIC DATA GENERATOR
===========================================

Purpose
-------
Generate synthetic UCS proving-ring readings and populate the user's
existing XLSM template.

IMPORTANT TEMPLATE MAPPING
--------------------------
Header:
D1 = BH ID
D2 = Depth
D3 = Diameter of Specimen (cm)
D4 = Initial Area A0 (Excel formula from D3)
D5 = Initial Height (cm)
D6 = Density (gm/cc)
D7 = Sample Weight Taken (Excel formula from D4*D5*D6)
D8 = PR Constant (kg/div), default 0.325

Observation table:
A11:A42 = SR No. 1 to 32
B11:B42 = fixed dial reading 0,50,100,...,1550
C11:C42 = =B/1000
D11:D42 = =(C/$D$5)*100
E11:E42 = =$D$4/(1-(D/100))
F11:F42 = synthetic PR reading generated by Python
G11:G42 = =F*$D$8
H11:H42 = =G/E

No CSV export.

Multiple-depth requirement
--------------------------
Every depth has its own:
- Depth
- Diameter
- Height
- Density
- Assigned UCS
- PR Constant
- Random Seed
- Soil Type
- Sample Type

BH ID is common to the project.
"""

import math
import os
import random
import shutil
import tkinter as tk
from pathlib import Path
from tkinter import ttk, filedialog, messagebox

try:
    from openpyxl import load_workbook
    OPENPYXL_OK = True
except ImportError:
    OPENPYXL_OK = False

try:
    import matplotlib
    matplotlib.use("TkAgg")
    from matplotlib.figure import Figure
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
    MPL_OK = True
except ImportError:
    MPL_OK = False


ROWS = list(range(11, 43))
DIAL_DIVISIONS = [i * 50 for i in range(32)]


SOIL_PROFILES = {
    "Soft Clay": {
        "peak": (7.0, 12.0),
        "residual": (0.78, 0.90),
        "toe": 0.12,
        "noise": 0.018,
        "drop": 0.55,
    },
    "Medium Clay": {
        "peak": (5.0, 8.5),
        "residual": (0.68, 0.82),
        "toe": 0.10,
        "noise": 0.016,
        "drop": 0.75,
    },
    "Stiff Clay": {
        "peak": (2.8, 5.5),
        "residual": (0.55, 0.72),
        "toe": 0.08,
        "noise": 0.014,
        "drop": 1.00,
    },
    "Very Stiff Clay": {
        "peak": (1.8, 4.0),
        "residual": (0.45, 0.65),
        "toe": 0.06,
        "noise": 0.013,
        "drop": 1.25,
    },
    "Silty Clay": {
        "peak": (4.0, 7.5),
        "residual": (0.62, 0.80),
        "toe": 0.10,
        "noise": 0.017,
        "drop": 0.85,
    },
    "Sandy Clay": {
        "peak": (3.0, 6.5),
        "residual": (0.58, 0.76),
        "toe": 0.08,
        "noise": 0.018,
        "drop": 0.95,
    },
}


def generate_ucs(
    target_ucs,
    diameter_cm,
    height_cm,
    ring_constant,
    soil_type,
    seed,
):
    """Generate the 32 PR observations for one depth."""

    if soil_type not in SOIL_PROFILES:
        raise ValueError("Invalid soil type.")

    rng = random.Random(seed)
    profile = SOIL_PROFILES[soil_type]

    area0 = math.pi * diameter_cm * diameter_cm / 4.0

    # Exact strain values represented by the template.
    strain = [
        (dial / 1000.0) / height_cm * 100.0
        for dial in DIAL_DIVISIONS
    ]

    # Peak strain is selected according to the soil type.
    peak_target = rng.uniform(*profile["peak"])
    peak_index = min(
        range(len(strain)),
        key=lambda i: abs(strain[i] - peak_target)
    )

    # Keep enough points after peak to show post-peak behaviour.
    peak_index = max(4, min(peak_index, 25))

    strength_factor = max(
        0.975,
        min(1.025, rng.gauss(1.0, 0.010))
    )
    target_actual = target_ucs * strength_factor

    normalized = []

    for i in range(32):
        if i <= peak_index:
            x = i / peak_index

            # Initial seating/toe followed by nonlinear hardening.
            if x <= 0.12:
                y = profile["toe"] * (x / 0.12) ** 1.55
            else:
                z = (x - 0.12) / 0.88
                y = profile["toe"] + (
                    1.0 - profile["toe"]
                ) * (
                    0.28 * z + 0.72 * z ** 0.62
                )

            y *= 1.0 + rng.gauss(
                0.0, profile["noise"] * 0.35
            )

        else:
            q = (
                (i - peak_index)
                / (31 - peak_index)
            )

            residual = rng.uniform(
                *profile["residual"]
            )

            y = 1.0 - (
                1.0 - residual
            ) * q ** profile["drop"]

            y *= 1.0 + rng.gauss(
                0.0, profile["noise"]
            )

        normalized.append(max(0.0, y))

    normalized[peak_index] = 1.0

    # Convert desired stress to PR reading.
    pr = []

    for i in range(32):
        area = area0 / (
            1.0 - strain[i] / 100.0
        )

        desired_stress = (
            target_actual * normalized[i]
        )

        ideal_pr = (
            desired_stress * area
            / ring_constant
        )

        # Simulated logger/proving-ring variation.
        if i < 3:
            factor = rng.uniform(0.94, 0.985)
        else:
            factor = rng.uniform(0.985, 1.015)

        reading = max(
            0.0,
            ideal_pr * factor
        )

        pr.append(int(round(reading)))

    # Avoid implausible downward movement before failure.
    for i in range(1, peak_index + 1):
        if pr[i] < pr[i - 1]:
            pr[i] = pr[i - 1]

    # Calculate actual stress after integer PR rounding.
    stress = []

    for i in range(32):
        area = area0 / (
            1.0 - strain[i] / 100.0
        )
        stress.append(
            pr[i] * ring_constant / area
        )

    actual_ucs = max(stress)
    actual_peak = stress.index(actual_ucs)

    return {
        "dial": DIAL_DIVISIONS[:],
        "strain": strain,
        "pr": pr,
        "stress": stress,
        "peak_index": actual_peak,
        "actual_ucs": actual_ucs,
        "area0": area0,
    }


def populate_xlsm(
    template_path,
    output_path,
    specimen,
    result,
):
    """Copy template and populate the Trial_01 sheet."""

    if not OPENPYXL_OK:
        raise RuntimeError(
            "openpyxl is not installed.\n\n"
            "Run:\n"
            "py -m pip install openpyxl"
        )

    if not os.path.isfile(template_path):
        raise FileNotFoundError(
            "Selected XLSM template was not found."
        )

    shutil.copy2(template_path, output_path)

    wb = load_workbook(
        output_path,
        keep_vba=True
    )

    if "Trial_01" not in wb.sheetnames:
        wb.close()
        raise ValueError(
            "The selected template does not contain "
            "a sheet named 'Trial_01'."
        )

    ws = wb["Trial_01"]

    # ----------------------------------------------------------
    # Header
    # ----------------------------------------------------------
    ws["D1"] = specimen["bh_id"]
    ws["D2"] = specimen["depth"]
    ws["D3"] = specimen["diameter"]

    # User requested these cells to be calculated in Excel.
    ws["D4"] = "=(PI()/4)*D3^2"

    ws["D5"] = specimen["height"]
    ws["D6"] = specimen["density"]

    # Volume = Area x Height; density in gm/cc gives gm.
    ws["D7"] = "=D4*D5*D6"

    ws["D8"] = specimen["ring_constant"]

    # Keep assigned UCS available in H2, as in the basic macro.
    ws["H2"] = specimen["ucs"]

    # ----------------------------------------------------------
    # Observation table
    # ----------------------------------------------------------
    for i, row in enumerate(ROWS):

        # A: SR No.
        ws.cell(row, 1).value = i + 1

        # B: fixed dial reading
        ws.cell(row, 2).value = DIAL_DIVISIONS[i]

        # C: dial reading in cm
        ws.cell(row, 3).value = (
            f"=B{row}/1000"
        )

        # D: axial strain
        ws.cell(row, 4).value = (
            f"=(C{row}/$D$5)*100"
        )

        # E: average cross-sectional area
        ws.cell(row, 5).value = (
            f"=$D$4/(1-(D{row}/100))"
        )

        # F: generated PR reading
        ws.cell(row, 6).value = result["pr"][i]

        # G: axial load
        ws.cell(row, 7).value = (
            f"=F{row}*$D$8"
        )

        # H: compressive stress
        ws.cell(row, 8).value = (
            f"=G{row}/E{row}"
        )

    # Optional sample information only if matching cells/labels
    # already exist in the supplied template. We do NOT invent a
    # fixed destination because it was not specified by the user.
    #
    # The information remains in the GUI/project data and is shown
    # in the generated filename/status.

    try:
        wb.calculation.fullCalcOnLoad = True
        wb.calculation.forceFullCalc = True
        wb.calculation.calcMode = "auto"
    except Exception:
        pass

    wb.save(output_path)
    wb.close()


class UCSApp:

    def __init__(self, root):
        self.root = root
        self.root.title(
            "AI-Assisted UCS Synthetic Data Generator"
        )
        self.root.geometry("1500x900")
        self.root.minsize(1200, 760)

        self.bh_id = tk.StringVar(
            value="BH-01"
        )
        self.template = tk.StringVar()
        self.status = tk.StringVar(
            value="Ready."
        )

        self.generated = {}
        self.selected = None

        self.build()

    # ==========================================================
    # GUI
    # ==========================================================
    def build(self):

        outer = ttk.Frame(
            self.root,
            padding=10
        )
        outer.pack(
            fill="both",
            expand=True
        )

        ttk.Label(
            outer,
            text=(
                "AI-Assisted UCS Synthetic Data Generator "
                "— Multiple Depth"
            ),
            font=("Segoe UI", 16, "bold")
        ).pack(
            anchor="w",
            pady=(0, 8)
        )

        # ------------------------------------------------------
        # Common project information
        # ------------------------------------------------------
        common = ttk.LabelFrame(
            outer,
            text="Project Information",
            padding=8
        )
        common.pack(
            fill="x",
            pady=(0, 8)
        )

        ttk.Label(
            common,
            text="BH ID:"
        ).grid(
            row=0, column=0,
            padx=5, pady=4
        )

        ttk.Entry(
            common,
            textvariable=self.bh_id,
            width=18
        ).grid(
            row=0, column=1,
            padx=5
        )

        ttk.Label(
            common,
            text=(
                "B11:B42 is fixed at 0, 50, 100 ... 1550. "
                "C/D/E/G/H are written as Excel formulas."
            )
        ).grid(
            row=0,
            column=2,
            columnspan=5,
            padx=20,
            sticky="w"
        )

        # ------------------------------------------------------
        # Multiple-depth input
        # ------------------------------------------------------
        box = ttk.LabelFrame(
            outer,
            text=(
                "MULTIPLE DEPTH INPUT — "
                "Soil Type and Sample Type are entered separately "
                "for EVERY depth"
            ),
            padding=8
        )
        box.pack(
            fill="x",
            pady=(0, 8)
        )

        columns = (
            "depth",
            "diameter",
            "height",
            "density",
            "ucs",
            "ring",
            "soil",
            "sample",
            "seed",
            "status",
        )

        self.tree = ttk.Treeview(
            box,
            columns=columns,
            show="headings",
            height=8
        )

        headings = [
            ("depth", "Depth (m)", 90),
            ("diameter", "Diameter (cm)", 105),
            ("height", "Height (cm)", 105),
            ("density", "Density (gm/cc)", 120),
            ("ucs", "Assigned UCS (kg/cm²)", 155),
            ("ring", "PR Constant (kg/div)", 145),
            ("soil", "Soil Type", 145),
            ("sample", "Sample Type", 105),
            ("seed", "Random Seed", 105),
            ("status", "Status", 145),
        ]

        for col, title, width in headings:
            self.tree.heading(
                col,
                text=title
            )
            self.tree.column(
                col,
                width=width,
                anchor="center"
            )

        self.tree.pack(
            fill="x",
            expand=True
        )

        self.tree.bind(
            "<<TreeviewSelect>>",
            self.on_select
        )

        self.tree.bind(
            "<Double-1>",
            self.edit_cell
        )

        buttons = ttk.Frame(box)
        buttons.pack(
            fill="x",
            pady=(7, 0)
        )

        ttk.Button(
            buttons,
            text="Add Depth",
            command=self.add_depth
        ).pack(
            side="left",
            padx=3
        )

        ttk.Button(
            buttons,
            text="Remove Selected",
            command=self.remove_selected
        ).pack(
            side="left",
            padx=3
        )

        ttk.Button(
            buttons,
            text="Clear All",
            command=self.clear_all
        ).pack(
            side="left",
            padx=3
        )

        ttk.Button(
            buttons,
            text="IMPORT EXCEL",
            command=self.import_excel_input
        ).pack(
            side="left",
            padx=(18, 3)
        )

        ttk.Button(
            buttons,
            text="Generate ALL Depths",
            command=self.generate_all
        ).pack(
            side="left",
            padx=(18, 3)
        )

        ttk.Label(
            buttons,
            text="Double-click any input cell to edit"
        ).pack(
            side="left",
            padx=15
        )

        # ------------------------------------------------------
        # Template
        # ------------------------------------------------------
        template_box = ttk.LabelFrame(
            outer,
            text="XLSM Template",
            padding=8
        )
        template_box.pack(
            fill="x",
            pady=(0, 8)
        )

        ttk.Entry(
            template_box,
            textvariable=self.template
        ).pack(
            side="left",
            fill="x",
            expand=True,
            padx=5
        )

        ttk.Button(
            template_box,
            text="Browse XLSM",
            command=self.browse_template
        ).pack(
            side="left",
            padx=5
        )

        # ------------------------------------------------------
        # Action buttons
        # ------------------------------------------------------
        action = ttk.Frame(outer)
        action.pack(fill="x", pady=(0, 8))

        action1 = ttk.Frame(action)
        action1.pack(fill="x", pady=(0, 5))

        ttk.Button(action1, text="Generate Selected", command=self.generate_selected).pack(side="left", padx=3)
        ttk.Button(action1, text="Preview Selected", command=self.preview_selected).pack(side="left", padx=3)
        ttk.Button(action1, text="Populate Selected XLSM", command=self.populate_selected).pack(side="left", padx=3)
        ttk.Button(action1, text="Populate ALL Depths", command=self.populate_all).pack(side="left", padx=(18, 3))

        # ======================================================
        # REPORT PLOT EXPORT - ALWAYS VISIBLE
        # ======================================================
        ttk.Button(
            action1,
            text="EXPORT PLOT",
            command=self.export_selected_plot
        ).pack(side="left", padx=(18, 3))

        ttk.Button(
            action1,
            text="EXPORT ALL PLOTS",
            command=self.export_all_plots
        ).pack(side="left", padx=3)

        ttk.Label(
            outer,
            text="REPORT EXPORT: Select a depth and click EXPORT PLOT, or click EXPORT ALL PLOTS.",
            foreground="#123B8A",
            font=("Segoe UI", 9, "bold")
        ).pack(fill="x", pady=(0, 5))

        # ------------------------------------------------------
        # Lower area
        # ------------------------------------------------------
        lower = ttk.Frame(outer)
        lower.pack(
            fill="both",
            expand=True
        )

        lower.columnconfigure(
            0, weight=1
        )
        lower.columnconfigure(
            1, weight=1
        )
        lower.rowconfigure(
            0, weight=1
        )

        plotbox = ttk.LabelFrame(
            lower,
            text="Stress–Strain Preview",
            padding=5
        )
        plotbox.grid(
            row=0,
            column=0,
            sticky="nsew",
            padx=(0, 5)
        )

        if MPL_OK:
            self.fig = Figure(
                figsize=(6.3, 5.2),
                dpi=100
            )
            self.ax = self.fig.add_subplot(111)

            self.canvas = FigureCanvasTkAgg(
                self.fig,
                master=plotbox
            )
            self.canvas.get_tk_widget().pack(
                fill="both",
                expand=True
            )
        else:
            self.fig = None
            self.ax = None
            self.canvas = None

            ttk.Label(
                plotbox,
                text=(
                    "Matplotlib is required.\n\n"
                    "Install:\n"
                    "py -m pip install matplotlib"
                )
            ).pack(
                expand=True
            )

        databox = ttk.LabelFrame(
            lower,
            text="Selected Depth — Generated Data",
            padding=5
        )
        databox.grid(
            row=0,
            column=1,
            sticky="nsew",
            padx=(5, 0)
        )

        frame = ttk.Frame(databox)
        frame.pack(
            fill="both",
            expand=True
        )

        self.data_tree = ttk.Treeview(
            frame,
            columns=(
                "sr",
                "dial",
                "cm",
                "strain",
                "pr",
                "load",
                "stress",
            ),
            show="headings"
        )

        scroll = ttk.Scrollbar(
            frame,
            orient="vertical",
            command=self.data_tree.yview
        )
        scroll.pack(
            side="right",
            fill="y"
        )

        self.data_tree.pack(
            side="left",
            fill="both",
            expand=True
        )

        self.data_tree.configure(
            yscrollcommand=scroll.set
        )

        data_heads = [
            ("sr", "SR", 50),
            ("dial", "Dial", 75),
            ("cm", "cm", 70),
            ("strain", "Strain %", 90),
            ("pr", "PR", 70),
            ("load", "Load kg", 90),
            ("stress", "Stress kg/cm²", 105),
        ]

        for col, title, width in data_heads:
            self.data_tree.heading(
                col,
                text=title
            )
            self.data_tree.column(
                col,
                width=width,
                anchor="center"
            )

        ttk.Label(
            outer,
            textvariable=self.status
        ).pack(
            anchor="w",
            pady=(6, 0)
        )

        # Start with two blank user-entry rows.
        self.add_depth()
        self.add_depth()

        self.clear_preview()

    # ==========================================================
    # DEPTH ROWS
    # ==========================================================
    def add_depth(self):
        n = len(
            self.tree.get_children()
        ) + 1

        self.tree.insert(
            "",
            "end",
            values=(
                "",
                "3.792",
                "7.611",
                "1.84",
                "1.733",
                "0.325",
                "Medium Clay",
                "UDS",
                str(1000 + n),
                "Not generated",
            )
        )

    def remove_selected(self):
        selected = self.tree.selection()

        if not selected:
            messagebox.showwarning(
                "No Selection",
                "Select a depth row first."
            )
            return

        for item in selected:
            self.tree.delete(item)

        self.generated.clear()
        self.selected = None
        self.clear_preview()

        self.status.set(
            "Selected depth row removed."
        )

    def clear_all(self):
        for item in self.tree.get_children():
            self.tree.delete(item)

        self.generated.clear()
        self.selected = None
        self.clear_preview()

        self.status.set(
            "All depth rows cleared."
        )

    def on_select(self, _event=None):
        selected = self.tree.selection()

        if not selected:
            return

        item = selected[0]
        self.selected = self.tree.index(item)

        if self.selected in self.generated:
            self.show_result(
                self.generated[self.selected]
            )
        else:
            self.clear_preview()
            self.status.set(
                "Depth selected. Generate it to preview."
            )

    def edit_cell(self, event):
        item = self.tree.identify_row(
            event.y
        )
        column = self.tree.identify_column(
            event.x
        )

        if not item or not column:
            return

        col_index = (
            int(column.replace("#", "")) - 1
        )

        # Status is read-only.
        if col_index == 9:
            return

        bbox = self.tree.bbox(
            item,
            column
        )

        if not bbox:
            return

        x, y, width, height = bbox

        values = list(
            self.tree.item(
                item,
                "values"
            )
        )

        if col_index == 6:
            editor = ttk.Combobox(
                self.tree,
                values=tuple(
                    SOIL_PROFILES.keys()
                ),
                state="readonly"
            )
            editor.set(values[col_index])

        elif col_index == 7:
            editor = ttk.Combobox(
                self.tree,
                values=("UDS", "SPT"),
                state="readonly"
            )
            editor.set(values[col_index])

        else:
            editor = ttk.Entry(
                self.tree
            )
            editor.insert(
                0,
                values[col_index]
            )

        editor.place(
            x=x,
            y=y,
            width=width,
            height=height
        )

        editor.focus_set()

        done = {"value": False}

        def commit(_event=None):
            if done["value"]:
                return

            done["value"] = True

            values[col_index] = (
                editor.get().strip()
            )

            values[9] = "Not generated"

            self.tree.item(
                item,
                values=values
            )

            self.generated.clear()

            editor.destroy()

            self.status.set(
                "Input changed. Generate again."
            )

        editor.bind(
            "<Return>",
            commit
        )
        editor.bind(
            "<FocusOut>",
            commit
        )

    # ==========================================================
    # INPUT / GENERATION
    # ==========================================================
    def read_row(self, index):
        items = self.tree.get_children()

        if index >= len(items):
            raise ValueError(
                "Invalid depth row."
            )

        v = self.tree.item(
            items[index],
            "values"
        )

        try:
            depth = float(v[0])
            diameter = float(v[1])
            height = float(v[2])
            density = float(v[3])
            ucs = float(v[4])
            ring = float(v[5])
            soil = str(v[6]).strip()
            sample = str(v[7]).strip().upper()
            seed = int(v[8])
        except Exception:
            raise ValueError(
                f"Invalid input in depth row {index + 1}."
            )

        if depth < 0:
            raise ValueError(
                "Depth cannot be negative."
            )
        if diameter <= 0:
            raise ValueError(
                "Diameter must be greater than zero."
            )
        if height <= 0:
            raise ValueError(
                "Height must be greater than zero."
            )
        if density <= 0:
            raise ValueError(
                "Density must be greater than zero."
            )
        if ucs <= 0:
            raise ValueError(
                "Assigned UCS must be greater than zero."
            )
        if ring <= 0:
            raise ValueError(
                "PR Constant must be greater than zero."
            )
        if soil not in SOIL_PROFILES:
            raise ValueError(
                "Select a valid Soil Type."
            )
        if sample not in ("UDS", "SPT"):
            raise ValueError(
                "Sample Type must be UDS or SPT."
            )

        return {
            "bh_id": (
                self.bh_id.get().strip()
                or "BH-01"
            ),
            "depth": depth,
            "diameter": diameter,
            "height": height,
            "density": density,
            "ucs": ucs,
            "ring_constant": ring,
            "soil": soil,
            "sample": sample,
            "seed": seed,
        }

    def set_status(self, index, value):
        items = self.tree.get_children()

        if index >= len(items):
            return

        vals = list(
            self.tree.item(
                items[index],
                "values"
            )
        )
        vals[9] = value

        self.tree.item(
            items[index],
            values=vals
        )

    def generate_one(self, index):
        specimen = self.read_row(index)

        result = generate_ucs(
            specimen["ucs"],
            specimen["diameter"],
            specimen["height"],
            specimen["ring_constant"],
            specimen["soil"],
            specimen["seed"],
        )

        data = {
            "specimen": specimen,
            "result": result,
        }

        self.generated[index] = data

        self.set_status(
            index,
            f"Generated {result['actual_ucs']:.3f}"
        )

        return data

    def generate_selected(self):
        if not self.tree.get_children():
            messagebox.showwarning(
                "No Depths",
                "Add a depth first."
            )
            return

        if self.selected is None:
            self.selected = 0
            self.tree.selection_set(
                self.tree.get_children()[0]
            )

        try:
            data = self.generate_one(
                self.selected
            )
            self.show_result(data)

            self.status.set(
                f"Depth {data['specimen']['depth']:.2f} m | "
                f"Soil: {data['specimen']['soil']} | "
                f"Sample: {data['specimen']['sample']} | "
                f"Assigned UCS: "
                f"{data['specimen']['ucs']:.3f} | "
                f"Generated UCS: "
                f"{data['result']['actual_ucs']:.3f} kg/cm²"
            )

        except Exception as exc:
            self.set_status(
                self.selected,
                "Error"
            )
            messagebox.showerror(
                "Generation Error",
                str(exc)
            )

    def generate_all(self):
        count = len(
            self.tree.get_children()
        )

        if count == 0:
            messagebox.showwarning(
                "No Depths",
                "Add at least one depth."
            )
            return

        self.generated.clear()
        errors = []

        for i in range(count):
            try:
                self.generate_one(i)
            except Exception as exc:
                self.set_status(
                    i,
                    "Error"
                )
                errors.append(
                    f"Row {i + 1}: {exc}"
                )

        if errors:
            messagebox.showerror(
                "Generation Error",
                "\n".join(errors)
            )
            return

        self.selected = 0
        self.tree.selection_set(
            self.tree.get_children()[0]
        )
        self.show_result(
            self.generated[0]
        )

        messagebox.showinfo(
            "Generation Complete",
            f"{count} depth(s) generated successfully."
        )

        self.status.set(
            f"Generated {count} depth(s)."
        )

    # ==========================================================
    # PREVIEW
    # ==========================================================
    def clear_preview(self):
        for item in self.data_tree.get_children():
            self.data_tree.delete(item)

        if self.ax is not None:
            self.ax.clear()
            self.ax.text(
                0.5,
                0.5,
                "Generate a depth to preview",
                ha="center",
                va="center",
                transform=self.ax.transAxes
            )
            self.ax.set_axis_off()
            self.canvas.draw_idle()

    def show_result(self, data):
        result = data["result"]

        for item in self.data_tree.get_children():
            self.data_tree.delete(item)

        for i in range(32):
            load = (
                result["pr"][i]
                * data["specimen"]["ring_constant"]
            )

            self.data_tree.insert(
                "",
                "end",
                values=(
                    i + 1,
                    result["dial"][i],
                    f"{result['dial'][i] / 1000:.3f}",
                    f"{result['strain'][i]:.3f}",
                    result["pr"][i],
                    f"{load:.2f}",
                    f"{result['stress'][i]:.3f}",
                )
            )

        self.draw_plot(data)

    def preview_selected(self):
        if self.selected is None:
            messagebox.showwarning(
                "No Selection",
                "Select a depth first."
            )
            return

        if self.selected not in self.generated:
            self.generate_selected()
        else:
            self.show_result(
                self.generated[self.selected]
            )

    def draw_plot(self, data):
        if self.ax is None:
            return

        specimen = data["specimen"]
        result = data["result"]

        x = result["strain"]
        y = result["stress"]
        p = result["peak_index"]

        self.ax.clear()
        self.ax.set_axis_on()

        self.ax.plot(
            x,
            y,
            marker="o",
            markersize=3.2,
            linewidth=1.4
        )

        self.ax.scatter(
            [x[p]],
            [y[p]],
            s=45,
            zorder=5
        )

        self.ax.annotate(
            f"UCS = {y[p]:.3f} kg/cm²\n"
            f"Peak strain = {x[p]:.2f}%",
            xy=(x[p], y[p]),
            xytext=(10, 10),
            textcoords="offset points",
            fontsize=8,
            bbox=dict(
                boxstyle="round,pad=0.3",
                facecolor="white",
                alpha=0.9
            ),
            arrowprops=dict(
                arrowstyle="->",
                linewidth=0.8
            )
        )

        self.ax.set_title(
            f"UCS Stress–Strain Curve | "
            f"{specimen['bh_id']} | "
            f"Depth {specimen['depth']:.2f} m | "
            f"{specimen['soil']} | "
            f"{specimen['sample']}",
            fontsize=11,
            fontweight="bold"
        )

        self.ax.set_xlabel(
            "Axial Strain, ε (%)"
        )
        self.ax.set_ylabel(
            "Compressive Stress, σ₀ (kg/cm²)"
        )
        self.ax.grid(
            True,
            linestyle="--",
            alpha=0.35
        )

        self.ax.set_xlim(
            0,
            max(20.0, max(x) * 1.03)
        )
        self.ax.set_ylim(
            0,
            max(y) * 1.12
        )

        self.fig.tight_layout()
        self.canvas.draw_idle()

    # ==========================================================
    # REPORT PLOT EXPORT
    # ==========================================================
    def export_report_plot(self, data, output_path):
        """Export a fixed-size A4 landscape report-ready UCS plot."""
        if not MPL_OK:
            raise RuntimeError(
                "Matplotlib is required for plot export.\n\n"
                "Install it with:\npy -m pip install matplotlib"
            )

        specimen = data["specimen"]
        result = data["result"]
        peak = result["peak_index"]
        ucs = float(result["stress"][peak])
        area0 = float(result["area0"])

        # Fixed A4 landscape page. Do NOT use bbox_inches='tight':
        # it can make figure-coordinate content appear tiny or displaced.
        fig = Figure(
            figsize=(11.69, 8.27),
            dpi=300,
            facecolor="white"
        )

        navy = "#123B8A"
        red = "#E32620"
        black = "#111111"
        light_blue = "#EAF2FA"

        # ----------------------------------------------------------
        # Page border
        # ----------------------------------------------------------
        fig.patches.append(
            matplotlib.patches.Rectangle(
                (0.008, 0.008), 0.984, 0.984,
                fill=False, linewidth=1.0,
                transform=fig.transFigure
            )
        )

        # ----------------------------------------------------------
        # Header
        # ----------------------------------------------------------
        fig.text(
            0.50, 0.958,
            "UNCONFINED COMPRESSION TEST (UCS)",
            ha="center", va="center",
            fontsize=17, fontweight="bold", color=navy
        )

        fig.lines.append(
            matplotlib.lines.Line2D(
                [0.02, 0.98], [0.925, 0.925],
                transform=fig.transFigure,
                linewidth=0.8, color=black
            )
        )

        # Top left: only BH ID, Depth, Sample Type.
        for label, value, y in [
            ("BH ID", specimen["bh_id"], 0.888),
            ("Depth", f"{specimen['depth']:.2f} m", 0.848),
            ("Sample Type", specimen["sample"], 0.808),
        ]:
            fig.text(
                0.035, y, label,
                fontsize=10.5, fontweight="bold"
            )
            fig.text(0.145, y, ":", fontsize=10.5)
            fig.text(
                0.165, y, str(value),
                fontsize=10.5, color=navy
            )

        # Specimen information (Column 2)
        for (label, value), y in zip(
            [
                ("Specimen Diameter (D)", f"{specimen['diameter']:.3f} cm"),
                ("Initial Area (A₀)", f"{area0:.2f} cm²"),
                ("Initial Height (H₀)", f"{specimen['height']:.3f} cm"),
            ],
            [0.888, 0.848, 0.808]
        ):
            fig.text(
                0.355, y, label,
                fontsize=10.5, fontweight="bold"
            )
            fig.text(0.535, y, ":", fontsize=10.5)
            fig.text(
                0.555, y, value,
                fontsize=10.5, color=navy
            )

        # Bulk Density & Proving Ring Constant (Column 3)
        ring_c = specimen.get("ring_constant", 0.325)
        for (label, value), y in zip(
            [
                ("Bulk Density (γ)", f"{specimen['density']:.2f} g/cc"),
                ("Proving Ring Const.", f"{float(ring_c):.4f} kg/div"),
            ],
            [0.888, 0.848]
        ):
            fig.text(
                0.680, y, label,
                fontsize=10.5, fontweight="bold"
            )
            fig.text(0.845, y, ":", fontsize=10.5)
            fig.text(
                0.865, y, value,
                fontsize=10.5, color=navy
            )

        fig.lines.append(
            matplotlib.lines.Line2D(
                [0.02, 0.98], [0.748, 0.748],
                transform=fig.transFigure,
                linewidth=0.8, color=black
            )
        )

        # ----------------------------------------------------------
        # Stress-strain graph
        # ----------------------------------------------------------
        ax = fig.add_axes([0.105, 0.335, 0.790, 0.365])

        ax.plot(
            result["strain"], result["stress"],
            marker="o", markersize=3.0,
            linewidth=1.45
        )

        peak_x = float(result["strain"][peak])

        ax.scatter(
            [peak_x], [ucs],
            s=42, zorder=5,
            color=red, edgecolor=black, linewidth=0.6
        )

        ax.annotate(
            f"UCS (qᵤ) = {ucs:.2f} kg/cm²",
            xy=(peak_x, ucs),
            xytext=(12, 12),
            textcoords="offset points",
            fontsize=9.2,
            fontweight="bold",
            color=red,
            arrowprops=dict(
                arrowstyle="->",
                color=red,
                linewidth=0.9
            )
        )

        ax.set_title(
            "STRESS – STRAIN CURVE",
            fontsize=12.5,
            fontweight="bold",
            color=navy,
            pad=8
        )

        ax.set_xlabel(
            "Axial Strain, ε (%)",
            fontsize=10.5,
            fontweight="bold",
            color=navy
        )

        ax.set_ylabel(
            "Compressive Stress, σ₀ (kg/cm²)",
            fontsize=10.5,
            fontweight="bold",
            color=navy
        )

        ax.grid(
            True,
            linestyle="--",
            linewidth=0.55,
            alpha=0.35
        )

        max_strain = max(float(v) for v in result["strain"])
        max_stress = max(float(v) for v in result["stress"])

        ax.set_xlim(0, max(20.0, max_strain * 1.02))
        ax.set_ylim(0, max(3.0, max_stress * 1.18))

        # ----------------------------------------------------------
        # Results heading
        # ----------------------------------------------------------
        fig.lines.append(
            matplotlib.lines.Line2D(
                [0.02, 0.98], [0.285, 0.285],
                transform=fig.transFigure,
                linewidth=0.8, color=black
            )
        )

        fig.text(
            0.50, 0.263,
            "UCS TEST RESULTS",
            ha="center", va="center",
            fontsize=12.5, fontweight="bold", color=navy
        )

        # ----------------------------------------------------------
        # Results table
        # ----------------------------------------------------------
        table_ax = fig.add_axes([0.020, 0.125, 0.960, 0.095])
        table_ax.set_axis_off()

        columns = [
            "Sample Depth\n(m)",
            "Sample Type",
            "Specimen Diameter\n(cm)",
            "Initial Height\n(cm)",
            "Density\n(g/cc)",
            "Initial Area\n(cm²)",
            "UCS (qᵤ)\n(kg/cm²)"
        ]

        values = [[
            f"{specimen['depth']:.2f}",
            specimen["sample"],
            f"{specimen['diameter']:.3f}",
            f"{specimen['height']:.3f}",
            f"{specimen['density']:.2f}",
            f"{area0:.2f}",
            f"{ucs:.2f}"
        ]]

        tbl = table_ax.table(
            cellText=values,
            colLabels=columns,
            cellLoc="center",
            colLoc="center",
            loc="center",
            bbox=[0, 0, 1, 1]
        )

        tbl.auto_set_font_size(False)
        tbl.set_fontsize(8.7)

        for (row, col), cell in tbl.get_celld().items():
            cell.set_edgecolor(black)
            cell.set_linewidth(0.6)

            if row == 0:
                cell.set_facecolor(light_blue)
                cell.set_text_props(fontweight="bold")
            elif col == 6:
                cell.set_text_props(
                    fontweight="bold",
                    color=red
                )

        # ----------------------------------------------------------
        # Remarks - one point only
        # ----------------------------------------------------------
        fig.text(
            0.020, 0.088,
            "Remarks:",
            fontsize=9.5,
            fontweight="bold"
        )

        fig.text(
            0.020, 0.060,
            "1. Unconfined Compression Test conducted as per IS 2720 (Part 10) – 1991.",
            fontsize=8.8
        )

        # Fixed page output: 3507 x 2481 pixels at 300 DPI.
        fig.savefig(
            output_path,
            dpi=300,
            facecolor="white",
            edgecolor="white",
            format="png"
        )

        fig.clear()

    def export_selected_plot(self):
        """Export the selected depth as a report-ready PNG."""
        if self.selected is None:
            messagebox.showwarning(
                "No Selection",
                "Select a depth first."
            )
            return

        try:
            if self.selected not in self.generated:
                self.generate_one(self.selected)

            data = self.generated[self.selected]
            specimen = data["specimen"]

            filename = (
                f"UCS_Report_{self.safe_filename(specimen['bh_id'])}_"
                f"SampleDepth_{specimen['depth']:.2f}m_"
                f"{specimen['sample']}.png"
            )

            output = filedialog.asksaveasfilename(
                title="Export UCS Report Plot",
                defaultextension=".png",
                initialfile=filename,
                filetypes=[("PNG Image", "*.png")]
            )

            if not output:
                return

            self.export_report_plot(data, output)
            self.status.set(f"Report plot exported: {output}")

            messagebox.showinfo(
                "Plot Exported",
                "Report-ready UCS plot exported successfully.\n\n"
                f"Saved to:\n{output}"
            )

        except Exception as exc:
            messagebox.showerror(
                "Plot Export Error",
                str(exc)
            )

    def export_all_plots(self):
        """Export one report-ready PNG for every depth."""
        count = len(self.tree.get_children())

        if count == 0:
            messagebox.showwarning(
                "No Depths",
                "Add at least one depth."
            )
            return

        errors = []
        self.generated.clear()

        for i in range(count):
            try:
                self.generate_one(i)
            except Exception as exc:
                self.set_status(i, "Error")
                errors.append(f"Row {i + 1}: {exc}")

        if errors:
            messagebox.showerror(
                "Generation Error",
                "\n".join(errors)
            )
            return

        folder = filedialog.askdirectory(
            title="Select Folder for UCS Report Plots"
        )

        if not folder:
            return

        created = []

        for i in range(count):
            try:
                data = self.generated[i]
                specimen = data["specimen"]

                filename = (
                    f"UCS_Report_{self.safe_filename(specimen['bh_id'])}_"
                    f"SampleDepth_{specimen['depth']:.2f}m_"
                    f"{specimen['sample']}.png"
                )

                output = Path(folder) / filename

                if output.exists():
                    output = output.with_name(
                        output.stem + "_new" + output.suffix
                    )

                self.export_report_plot(data, str(output))
                self.set_status(i, "Plot exported")
                created.append(str(output))

            except Exception as exc:
                self.set_status(i, "Plot error")
                errors.append(
                    f"Depth row {i + 1}: {exc}"
                )

        if errors:
            messagebox.showwarning(
                "Plot Export Completed",
                f"{len(created)} plot(s) created.\n\n"
                + "\n".join(errors)
            )
        else:
            messagebox.showinfo(
                "Plot Export Complete",
                f"{len(created)} report-ready plot(s) created."
            )

        self.status.set(
            f"Exported {len(created)} UCS report plot(s)."
        )

    # ==========================================================
    # EXCEL INPUT IMPORT
    # ==========================================================
    def import_excel_input(self):
        """Import multiple-depth input rows from an Excel .xlsx file."""
        if not OPENPYXL_OK:
            messagebox.showerror(
                "Excel Import Error",
                "openpyxl is not installed.\n\n"
                "Run:\npy -m pip install openpyxl"
            )
            return

        f = filedialog.askopenfilename(
            title="Select UCS Input Excel File",
            filetypes=[("Excel Workbook", "*.xlsx")]
        )
        if not f:
            return

        try:
            wb = load_workbook(f, data_only=True, read_only=True)
            ws = wb.active

            headers = [str(c.value).strip() if c.value is not None else ""
                       for c in ws[1]]

            required = [
                "Depth", "Diameter (cm)", "Height (cm)",
                "Density (gm/cc)", "Assigned UCS (kg/cm²)",
                "PR Constant (kg/div)", "Soil Type",
                "Sample Type", "Random Seed"
            ]

            # Accept a few natural header variants while keeping the
            # input template simple and explicit.
            aliases = {
                "Depth": ["Depth", "Depth (m)"],
                "Diameter (cm)": ["Diameter (cm)", "Diameter"],
                "Height (cm)": ["Height (cm)", "Height"],
                "Density (gm/cc)": ["Density (gm/cc)", "Density (g/cc)", "Density"],
                "Assigned UCS (kg/cm²)": [
                    "Assigned UCS (kg/cm²)", "Assigned UCS", "UCS"
                ],
                "PR Constant (kg/div)": [
                    "PR Constant (kg/div)", "PR Constant", "Ring Constant"
                ],
                "Soil Type": ["Soil Type", "Soil"],
                "Sample Type": ["Sample Type", "Sample"],
                "Random Seed": ["Random Seed", "Seed"],
            }

            index_map = {}
            for key, options in aliases.items():
                found = None
                for option in options:
                    if option in headers:
                        found = headers.index(option)
                        break
                if found is None:
                    raise ValueError(
                        f"Missing required column: {key}"
                    )
                index_map[key] = found

            # Optional BH ID column. If present, use it as the common BH ID.
            bh_idx = None
            for option in ("BH ID", "BH_ID", "Borehole ID"):
                if option in headers:
                    bh_idx = headers.index(option)
                    break

            rows = []
            for excel_row in ws.iter_rows(min_row=2, values_only=True):
                if not any(v is not None and str(v).strip() != "" for v in excel_row):
                    continue

                def val(key):
                    return excel_row[index_map[key]]

                row = [
                    "" if val("Depth") is None else val("Depth"),
                    "" if val("Diameter (cm)") is None else val("Diameter (cm)"),
                    "" if val("Height (cm)") is None else val("Height (cm)"),
                    "" if val("Density (gm/cc)") is None else val("Density (gm/cc)"),
                    "" if val("Assigned UCS (kg/cm²)") is None else val("Assigned UCS (kg/cm²)"),
                    "" if val("PR Constant (kg/div)") is None else val("PR Constant (kg/div)"),
                    "" if val("Soil Type") is None else val("Soil Type"),
                    "" if val("Sample Type") is None else val("Sample Type"),
                    "" if val("Random Seed") is None else val("Random Seed"),
                    "Not generated",
                ]
                rows.append(row)

                if bh_idx is not None and excel_row[bh_idx] is not None:
                    imported_bh = str(excel_row[bh_idx]).strip()
                    if imported_bh:
                        self.bh_id.set(imported_bh)

            wb.close()

            if not rows:
                raise ValueError("No input data rows were found in the Excel file.")

            # Replace current GUI depth rows with imported rows.
            for item in self.tree.get_children():
                self.tree.delete(item)

            self.generated.clear()
            self.selected = None

            for row in rows:
                self.tree.insert("", "end", values=tuple(row))

            self.clear_preview()
            self.status.set(
                f"Imported {len(rows)} depth(s) from Excel."
            )
            messagebox.showinfo(
                "Excel Import Complete",
                f"{len(rows)} depth(s) imported successfully."
            )

        except Exception as exc:
            messagebox.showerror(
                "Excel Import Error",
                str(exc)
            )

    # ==========================================================
    # XLSM
    # ==========================================================
    def browse_template(self):
        f = filedialog.askopenfilename(
            title="Select UCS XLSM Template",
            filetypes=[
                ("Excel Macro Workbook", "*.xlsm")
            ]
        )

        if f:
            self.template.set(f)

    def get_template(self):
        f = self.template.get().strip()

        if not f:
            f = filedialog.askopenfilename(
                title="Select UCS XLSM Template",
                filetypes=[
                    ("Excel Macro Workbook", "*.xlsm")
                ]
            )

            if not f:
                return None

            self.template.set(f)

        if not os.path.isfile(f):
            messagebox.showerror(
                "Template Error",
                "Selected XLSM file does not exist."
            )
            return None

        return f

    @staticmethod
    def safe_filename(text):
        for ch in '<>:"/\\|?*':
            text = text.replace(ch, "_")
        return text.replace(" ", "_")

    def output_name(self, specimen):
        bh = self.safe_filename(
            specimen["bh_id"]
        )

        return (
            f"UCS_{bh}_Depth_"
            f"{specimen['depth']:.2f}m_"
            f"{specimen['sample']}.xlsm"
        )

    def populate_selected(self):
        if self.selected is None:
            messagebox.showwarning(
                "No Selection",
                "Select a depth first."
            )
            return

        try:
            if self.selected not in self.generated:
                self.generate_selected()

            if self.selected not in self.generated:
                return

            template = self.get_template()

            if not template:
                return

            data = self.generated[
                self.selected
            ]
            specimen = data["specimen"]

            output = filedialog.asksaveasfilename(
                title="Save Populated UCS XLSM",
                defaultextension=".xlsm",
                initialfile=self.output_name(
                    specimen
                ),
                filetypes=[
                    ("Excel Macro Workbook", "*.xlsm")
                ]
            )

            if not output:
                return

            populate_xlsm(
                template,
                output,
                specimen,
                data["result"]
            )

            self.set_status(
                self.selected,
                "XLSM populated"
            )

            messagebox.showinfo(
                "Completed",
                f"Depth {specimen['depth']:.2f} m populated.\n\n"
                f"Soil Type: {specimen['soil']}\n"
                f"Sample Type: {specimen['sample']}\n"
                f"Assigned UCS: {specimen['ucs']:.3f} kg/cm²\n"
                f"Generated UCS: "
                f"{data['result']['actual_ucs']:.3f} kg/cm²\n\n"
                f"Saved:\n{output}"
            )

        except Exception as exc:
            messagebox.showerror(
                "XLSM Error",
                str(exc)
            )

    def populate_all(self):
        count = len(
            self.tree.get_children()
        )

        if count == 0:
            messagebox.showwarning(
                "No Depths",
                "Add at least one depth."
            )
            return

        template = self.get_template()

        if not template:
            return

        # Generate all first.
        self.generated.clear()

        errors = []

        for i in range(count):
            try:
                self.generate_one(i)
            except Exception as exc:
                self.set_status(
                    i,
                    "Error"
                )
                errors.append(
                    f"Depth row {i + 1}: {exc}"
                )

        if errors:
            messagebox.showerror(
                "Generation Error",
                "\n".join(errors)
            )
            return

        folder = filedialog.askdirectory(
            title=(
                "Select Folder for Populated "
                "UCS Templates"
            )
        )

        if not folder:
            return

        created = []

        for i in range(count):
            data = self.generated[i]
            specimen = data["specimen"]

            output = (
                Path(folder)
                / self.output_name(specimen)
            )

            # Prevent accidental overwrite.
            if output.exists():
                output = (
                    output.with_name(
                        output.stem
                        + "_new"
                        + output.suffix
                    )
                )

            try:
                populate_xlsm(
                    template,
                    str(output),
                    specimen,
                    data["result"]
                )

                self.set_status(
                    i,
                    "XLSM populated"
                )

                created.append(str(output))

            except Exception as exc:
                self.set_status(
                    i,
                    "XLSM error"
                )
                errors.append(
                    f"Depth {specimen['depth']:.2f} m: {exc}"
                )

        if errors:
            messagebox.showwarning(
                "Population Completed",
                f"{len(created)} file(s) created.\n\n"
                + "\n".join(errors)
            )
        else:
            messagebox.showinfo(
                "Population Complete",
                f"{len(created)} populated XLSM file(s) created."
            )

        self.status.set(
            f"Created {len(created)} populated XLSM file(s)."
        )


def main():
    root = tk.Tk()
    app = UCSApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()
